language: php
install:
    composer install
php:
  - 5.5
  - 5.6
  - hhvm
  - 7.0
  - 7.1

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
